name: example
on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step3
        name: step1_name
        run: echo "test=hellooooooooo" >> $GITHUB_OUTPUT
      - name: step2_name
        run: echo ${{steps.step3.outputs.test}}
